Repository neuralmagic/sparseml, pull requests merged in 2023-06, with the labels that each got.

#1595 Remove keras tests from GHA
  .github/workflows/test-check.yaml
Labels: mle-team

#1596 [Cherry-pick] Remove keras tests from GHA (#1595)
  .github/workflows/test-check.yaml
Labels: mle-team

#1580 [BugFix]: Limit torch version installed by ultralytics
  README.md
  docs/source/installation.md
  setup.py
Labels: bug, 1.5 release

#1597 [Bug-fix] YOLOv8 export docs update
  src/sparseml/yolov8/README.md
Labels: mle-team

#1598 [Cherry-Pick] YOLOv8 export docs update (#1597)
  src/sparseml/yolov8/README.md
Labels: mle-team

#1599 Add trainer to yolov8 validator when calling w/o recipe
  src/sparseml/yolov8/trainers.py
Labels: bug, 1.5 release

#1600 [Cherry Pick]Add trainer to validator when calling w/o recipe
  src/sparseml/yolov8/trainers.py
Labels: bug, 1.5 release

#1606 Remove tensorflow-v1 tests from GHA
  .github/workflows/test-check.yaml
Labels: mle-team

#1611 Deprecate Py37
  DEVELOPING.md
  README.md
  docs/source/installation.md
  setup.py
  src/sparseml/pytorch/image_classification/utils/helpers.py
Labels: mle-team

#1620 [cherry-pick 1.5.1] Fix yolov8 training error
  src/sparseml/version.py
  src/sparseml/yolov8/default.yaml
Labels: bug, mle-team

#1617 Update Developing Markdown
  DEVELOPING.md
Labels: documentation

#1633 Add accelerate package dep for transformers
  setup.py
Labels: mle-team

#1625 [BugFix] Hide `sparseml.benchmark`
  setup.py
  src/sparseml/benchmark/info.py
Labels: bug, mle-team
